### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dfallman** [DinkDonk/kitty-icon#10]
Love these icons!

As for the installation, I'm not sure if this has changed in recent versions of macOS (?), but I had trouble dragging and dropping the icons from the finder onto the app icon in the "more info" panel.

Another (perhaps simpler) way to install is to just select the two files, copy them, select the app icon at the top of "more info" panel, and hit paste.

**Comment by DinkDonk** [comment]
<img width="379" alt="Screenshot 2024-06-06 at 19 17 55" src="https://github.com/DinkDonk/kitty-icon/assets/3882374/3f18d362-950c-46b6-aeef-5a7147828513">
It works fine on all versions of MacOS. The mechanics of changing application icons hasn't changed since classic Mac OS system 5 – it's the small icon at the top right of the info pane (see attached image)
